version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1 \
              bash \
              jq \
              wget \
              curl
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=docker -t docker .
      - deploy:
          name: Push Docker image
          command: |
            IMAGE_NAME="amsterdam-mapitout-backend"
            LOGIN="$(aws ecr get-login)"
            ${LOGIN}
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag docker "${ECR_ENDPOINT}/${IMAGE_NAME}:latest"
              docker push "${ECR_ENDPOINT}/${IMAGE_NAME}:latest"
            fi
            docker tag docker "${ECR_ENDPOINT}/${IMAGE_NAME}:${CIRCLE_BRANCH}"
            docker push "${ECR_ENDPOINT}/${IMAGE_NAME}:${CIRCLE_BRANCH}"
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              wget https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy
              chmod +x ecs-deploy
              ./ecs-deploy -c Includable -n "${IMAGE_NAME}" -i "${ECR_ENDPOINT}/${IMAGE_NAME}:latest" -t 240
            fi
workflows:
  version: 2
  workflow:
    jobs:
      - build:
          context: includable-ecs
